### ISSUE TITLE
Error occured. Cannot read properties of null (reading 'updateTabIcon')

### ISSUE THREAD

**Issue by ivan-vilches** [codecompanion-ai/code-companion#105]
hello folks i downloaded for mac i use mac m1 
then i added the api key for open ai and claude sonnet 
when i use all time show me this:
Error occured. Cannot read properties of null (reading 'updateTabIcon')
also 
Error occured. Connection error.
how i can fix it?
thanks you

**Comment by codecompanion-ai** [comment]
> updateTabIcon

Can you check what version you have?  (Under settings where API keys are)

Should be 6.1.3+

If still happening with latest please let me know

**Comment by ivan-vilches** [comment]
Its 6.1.3 
<img width="298" alt="Captura de pantalla 2024-07-29 a la(s) 11 25 31" src="https://github.com/user-attachments/assets/36e23e33-b28a-493b-9aae-904d28cdc181">
I'm suspecting it happen when i choose claude sonnet i will keep testing later , maybe the api have some resctrictions.
thanks you for the quick answer

**Comment by codecompanion-ai** [comment]
> with gpt 4 mini [ <img alt="Captura de pantalla 2024-07-29 a la(s) 11 29 54" width="559" src="https://private-user-images.githubusercontent.com/982720/353134434-b8696e57-8b1e-4b11-8d22-1759bdf88d2f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyNjg1NDcsIm5iZiI6MTcyMjI2ODI0NywicGF0aCI6Ii85ODI3MjAvMzUzMTM0NDM0LWI4Njk2ZTU3LThiMWUtNGIxMS04ZDIyLTE3NTliZGY4OGQyZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyOVQxNTUwNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMzk1YjI3NzMzZTk2YzU1MDY0MGM2OGNlYjY0OTJlYmIyODI1MmRlMTEyZTc5MDNlNGM1YjRhZWQ4YmI4MDBiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pJIGmfr4BCyhBOHhOk6za0YNoRiaBlJzlYwCLa_8sqI"> ](url)

There was some API outage this morning for me as well. 
I think this is just temporary. Seems to be working better now

**Comment by ivan-vilches** [comment]
any plans to make it works with deepseek coder v2 ?

**Comment by codecompanion-ai** [comment]
> any plans to make it works with deepseek coder v2 ?

I gave it a try. Great model. 

Few issues I had:
- was very slow
- doesn't support function calling (there are workarounds for this to make it work, just will take some time)

I've gotten a lot of requests to add support for other open models and ollama, openrouter etc. 
Its on the road map. But I have few other things that are higher priority. 
So its going to be a while before I add more model options. 

One more thing, the only good model right now is Sonnet 3.5
Even if I add any other models, they will not perform well and people will blame the app. 

So this is another reason why its not a priority right now.
