### ISSUE TITLE
Add file tree for fine-grained context management

### ISSUE THREAD

**Issue by TeemuSo** [codecompanion-ai/code-companion#114]
Adding a file-tree view into the UI, where users can select relevant context files can greatly reduce the amount of tokens required for generation.

**Background:**
Thank you for building such a great open-source tool!

My biggest issue with AI coding tools is that they're trying to "intelligently" find relevant code snippets or code files, or then you need to prompt the full codebase. When projects get larger, this requires me to write a lot of boilerplate prompting to guide LLM to select correct files for referencing, just to make sure the LLM _possibly_ finds the relevant snippet I'm talking about.

I've built a small vscode extension for myself where you can select files to be referenced from a Github filetree, and it works great for selecting the appropriate context and controlling context length. Similar approach could be used here to increase the transparency of token usage and reduce unnecessary file browsing.

**Comment by codecompanion-ai** [comment]
> Adding a file-tree view into the UI, where users can select relevant context files can greatly reduce the amount of tokens required for generation.
> 
> **Background:** Thank you for building such a great open-source tool!
> 
> My biggest issue with AI coding tools is that they're trying to "intelligently" find relevant code snippets or code files, or then you need to prompt the full codebase. When projects get larger, this requires me to write a lot of boilerplate prompting to guide LLM to select correct files for referencing, just to make sure the LLM _possibly_ finds the relevant snippet I'm talking about.
> 
> I've built a small vscode extension for myself where you can select files to be referenced from a Github filetree, and it works great for selecting the appropriate context and controlling context length. Similar approach could be used here to increase the transparency of token usage and reduce unnecessary file browsing.



This is an excellent point. I can relate to this problem as I encounter it often.

I’ve been working on a solution for this recently, and I believe it’s going to be one of the most important features of the app. I’m taking a slightly different and broader approach.

It’s not just about the files included. Many projects utilize specific libraries, testing frameworks, unique file organization, namespaces, UI libraries or custom components, and established design patterns across the project.

It’s similar to when a new software engineer joins a project—first they need to study and understand these aspects to complete tasks within the project’s standards and conventions.

I’m actively working on this now, and I believe it will be a game changer.

Right now app has an "Executor".
Working on adding "Research/Planning/Memory"  step before Execution that will understand the project, conventions and based on your feedback it would make sense to make it editable so User can make adjustments (remove / add files to context etc) before task goes into execution phase.

**Comment by TeemuSo** [comment]
> > Adding a file-tree view into the UI, where users can select relevant context files can greatly reduce the amount of tokens required for generation.
> > **Background:** Thank you for building such a great open-source tool!
> > My biggest issue with AI coding tools is that they're trying to "intelligently" find relevant code snippets or code files, or then you need to prompt the full codebase. When projects get larger, this requires me to write a lot of boilerplate prompting to guide LLM to select correct files for referencing, just to make sure the LLM _possibly_ finds the relevant snippet I'm talking about.
> > I've built a small vscode extension for myself where you can select files to be referenced from a Github filetree, and it works great for selecting the appropriate context and controlling context length. Similar approach could be used here to increase the transparency of token usage and reduce unnecessary file browsing.
> 
> This is an excellent point. I can relate to this problem as I encounter it often.
> 
> I’ve been working on a solution for this recently, and I believe it’s going to be one of the most important features of the app. I’m taking a slightly different and broader approach.
> 
> It’s not just about the files included. Many projects utilize specific libraries, testing frameworks, unique file organization, namespaces, UI libraries or custom components, and established design patterns across the project.
> 
> It’s similar to when a new software engineer joins a project—first they need to study and understand these aspects to complete tasks within the project’s standards and conventions.
> 
> I’m actively working on this now, and I believe it will be a game changer.
> 
> Right now app has an "Executor". Working on adding "Research/Planning/Memory" step before Execution that will understand the project, conventions and based on your feedback it would make sense to make it editable so User can make adjustments (remove / add files to context etc) before task goes into execution phase.

I'm glad to hear! If I understood correctly, first thing with a task you "Initialize" the agent to include the project-specific configurations to the prompt? If its performed chat turn, I see the possibility of wasting tokens when doing trivial tasks.

In my small plugin I also have a checkbox for including the schema of the repository, and it helps a lot when cross-referencing between files or brainstorming infra changes

**Comment by codecompanion-ai** [comment]
@TeemuSo 

As a first step I am doing classification of the user task. 
If simple task, than no research/planning is needed to reduce token usage like you said.

**Comment by codecompanion-ai** [comment]
Done
