### ISSUE TITLE
Add debug logs to show prompts

### ISSUE THREAD

**Issue by TeemuSo** [codecompanion-ai/code-companion#115]
As a user, I would like to see what prompts are passed under the hood, so I can optimize my tool usage or propose more features for controlling the token flow. There could be a button on the top right corner next to chat history, which would show the processed prompts, similar to some agentic frameworks like langchain

**Comment by codecompanion-ai** [comment]
> As a user, I would like to see what prompts are passed under the hood, so I can optimize my tool usage or propose more features for controlling the token flow. There could be a button on the top right corner next to chat history, which would show the processed prompts, similar to some agentic frameworks like langchain

You can see the log already

Go to system menu of the app and click on "Download Chat Logs"
