### ISSUE TITLE
Why did you banned me on the Discord?

### ISSUE THREAD

**Issue by PierrunoYT** [codecompanion-ai/code-companion#32]
Why did you banned me on the Discord? I tried to contact you multiple times and I reported the bugs but I never got any reply. Do you think this is correct?

**Comment by codecompanion-ai** [comment]
> Why did you banned me on the Discord? I tried to contact you multiple times and I reported the bugs but I never got any reply. Do you think this is correct?

You just keep spamming the channel. 
Your bug reports don't make any sense and don't provide any usefull information.

If you don't like the app, just stop using it.

Spamming discord, github and all other accounts is not acceptable.

**Comment by PierrunoYT** [comment]
I tried to contact you but you did not replied. I like the app but since you changed something to it, it got broken, I would like to talk to you via DM but I did not get any answer
