### ISSUE TITLE
Unknown Bug

### ISSUE THREAD

**Issue by PierrunoYT** [codecompanion-ai/code-companion#59]
![grafik](https://github.com/codecompanion-ai/code-companion/assets/95778421/6a67749c-2184-47ad-a28e-59fd2fad9a85)

**Comment by PierrunoYT** [comment]
![grafik](https://github.com/codecompanion-ai/code-companion/assets/95778421/a15127bf-4b9a-43c8-ac3f-6de090d77706)

**Comment by codecompanion-ai** [comment]
These are just model limitations
