### ISSUE TITLE
Issues with Claude and the new DIFF feature

### ISSUE THREAD

**Issue by claudio-silva** [codecompanion-ai/code-companion#73]
I'm using Claude Sonnet and after a few code changing iterations it either:

1. starts writing badly formatted DIFFs that are displayed as DIFF-encoded text instead of a nicely formatted diff table, or
2. proposes an empty set of changes, sometimes with an indication of `Invalid line range: XXX-YYY`, but usually with no visible error message.

Either way, no changes are actually applied.
Allowing it to proceed keeps it in a loop doing the same thing again and again.

**Erasing part of the conversation and continuing from an earlier point is the only solution that allows the work to be resumed successfully.**

Additionally, using the following prompt was also somewhat effective in breaking the loop, if applied to a not-very-long conversation:

>Make sure you use the correct DIFF syntax for the file modification function.
>Even a mistake in a single character will make the patching process fail.
>Also take notice of error messages resulting from applying DIFFs and act to fix them.

To which it replies:
> Thank you for the reminder about using the correct DIFF syntax. I apologize for any confusion earlier. Let's proceed with the necessary changes to address the issues you've mentioned. I'll make sure to use the correct DIFF syntax for file modifications and pay attention to any error messages that might occur during the process.

And then proceeds to write a correct DIFF, well, at least sometimes...

Note: sometimes, accepting an empty set of changes is followed by a new set with actual changes, but if the conversation is long, it won't happen, and it will just keep proposing empty changes and then, if I say "No changes were proposed", it apologizes and then repeats the same empty set again.

**Comment by claudio-silva** [comment]
Sometimes, seemingly randomly, Claude just applies all changes to a file with multiple operations in a singe reply, neither asking for confirmation of each operation, nor displaying any DIFF.
Even worse, it seems all those operations were not actually carried out and Claude then says the whole project was implemented, when, in fact, it was not!
For example, it may say something like this (in a single response):
```
Let's update file XXX file to do YYY.
File XXX was updated successfully.
Now that we've added YYY, lets move on to the next item: ZZZ.
(...)
To implement unit tests, we'll create a new file called test_YYY.py in the same directory.
File test_YYY.py created successfully.
Great! We've created a basic set of unit tests for our core functions.
Now, let's move on to the next item (...)
```
Perhaps it got lazy and faked the responses, saying it did all of that, when the function for updating/creating a file was not even called?

As for the problem of the infinite loop with no changes being applied, the final workaround that provided the best results was to prompt Claude to write a description of the project into a README.md file, also describing what was implemented, what was still not implemented and the current issues.
Then I started a new blank conversation and just said:

> Read README.md and continue implementing the remaining changes.

The first few iterations run great, but then it starts degrading again.

**Comment by codecompanion-ai** [comment]
> Sometimes, seemingly randomly, Claude just applies all changes to a file with multiple operations in a singe reply, neither asking for confirmation of each operation, nor displaying any DIFF. Even worse, it seems all those operations were not actually carried out and Claude then says the whole project was implemented, when, in fact, it was not! For example, it may say something like this (in a single response):
> 
> ```
> Let's update file XXX file to do YYY.
> File XXX was updated successfully.
> Now that we've added YYY, lets move on to the next item: ZZZ.
> (...)
> To implement unit tests, we'll create a new file called test_YYY.py in the same directory.
> File test_YYY.py created successfully.
> Great! We've created a basic set of unit tests for our core functions.
> Now, let's move on to the next item (...)
> ```
> 
> Perhaps it got lazy and faked the responses, saying it did all of that, when the function for updating/creating a file was not even called?
> 
> As for the problem of the infinite loop with no changes being applied, the final workaround that provided the best results was to prompt Claude to write a description of the project into a README.md file, also describing what was implemented, what was still not implemented and the current issues. Then I started a new blank conversation and just said:
> 
> > Read README.md and continue implementing the remaining changes.
> 
> The first few iterations run great, but then it starts degrading again.

Hi Claudio!

Glad to see you still using the app. I think you are like one of the first users :) 

As always great feedback!

Regarding your note above: Claude is hallucinating!

I have seen this a lot.  More often on longer conversation. Deleting that message and retrying or adding a comment like "execute one command at a time"  seems to help as well


It seems like it happens only in some situations, I am trying to figure out how to reduce these hallucinations 


Claude is really good at coding and very fast - when it works. 

I'll try to get it to work more reliably

**Comment by claudio-silva** [comment]
Hi Alex,

I'm glad you still remember me :-)

I have been trying it out from time to time to see if it has evolved enough to be actually useful for daily usage. Now, with the new Sonnet 3.5, I decided to give it a spin again, as this new model is known for its great coding abilities.

Unfortunately, issues like this one prevent the tool from being truly useful, at least for iterating on a project. The longer the conversation, the more issues appear, and the worse the results get.
For the initial development of a prototype, it works fine.

I understand this issue is inherent to the way these models work, which makes them unreliable, so it is not actually the app's fault.

I hope you find a way to substantially reduce these issues.

I still believe this app deserves much more recognition than it has been getting!
I'm sure it has been flying below the radar for most people.

**Comment by codecompanion-ai** [comment]
> Hi Alex,
> 
> I'm glad you still remember me :-)
> 
> I have been trying it out from time to time to see if it has evolved enough to be actually useful for daily usage. Now, with the new Sonnet 3.5, I decided to give it a spin again, as this new model is known for its great coding abilities.
> 
> Unfortunately, issues like this one prevent the tool from being truly useful, at least for iterating on a project. The longer the conversation, the more issues appear, and the worse the results get. For the initial development of a prototype, it works fine.
> 
> I understand this issue is inherent to the way these models work, which makes them unreliable, so it is not actually the app's fault.
> 
> I hope you find a way to substantially reduce these issues.
> 
> I still believe this app deserves much more recognition than it has been getting! I'm sure it has been flying below the radar for most people.

Claudio, 

Give it a try now. Claude Sonnet shouldn't hallucinate in the latest update (5.25.9)
