### ISSUE TITLE
Error in web searches

### ISSUE THREAD

**Issue by claudio-silva** [codecompanion-ai/code-companion#78]
When performing a web search, we get this error:
```
Error occurred. 404 The model gpt-3.5-turbo-0613 has been deprecated, (...)
```
How to reproduce:
```
search the web to find out how who won the European soccer championship
```
Also, some of the web searches do not trigger the confirmation prompt before being executed.

**Comment by claudio-silva** [comment]
Oddly, I also got this error in the middle of a session of code generation, right after I clicked Approve to approve a set of proposed changes.
The model then proceeded as if nothing happened.

**Comment by codecompanion-ai** [comment]
should be fixed also
