### ISSUE TITLE
Chat history not working

### ISSUE THREAD

**Issue by claudio-silva** [codecompanion-ai/code-companion#79]
New conversations are not being added to the chat history sidebar.

**Comment by elcous** [comment]
> New conversations are not being added to the chat history sidebar.

By default, not all conversations saved. 

To save conversation use Cmd + S or click on the icon in the header to save chat

**Comment by claudio-silva** [comment]
Oh, I see...
Unfortunately, the icon was not clear at all. It says "Save chat" indeed, but I thought it was meant to save the chat into an external file.
Suggestion: changing the tooltip to "Save chat to history" would make it clearer.

**Comment by codecompanion-ai** [comment]
> Oh, I see... Unfortunately, the icon was not clear at all. It says "Save chat" indeed, but I thought it was meant to save the chat into an external file. Suggestion: changing the tooltip to "Save chat to history" would make it clearer.

Awesome, thanks for feedback! I will check if I can find a better icon in addition to changing label so it doesn't look like "export"

**Comment by claudio-silva** [comment]
It's fine now. 👍
