### ISSUE TITLE
Cannot read properties of undefined

### ISSUE THREAD

**Issue by claudio-silva** [codecompanion-ai/code-companion#80]
Context:
```
Let's start by updating the main component file:

Error occured. Cannot read properties of undefined (reading 'endsWith')
```
Using Claude 3.5

**Comment by claudio-silva** [comment]
It's stuck in a loop :-(
I'll have to start a new chat and try to resume the task from there,

**Comment by codecompanion-ai** [comment]
> Context:
> 
> ```
> Let's start by updating the main component file:
> 
> Error occured. Cannot read properties of undefined (reading 'endsWith')
> ```
> 
> Using Claude 3.5

should be fixed also now
