### ISSUE TITLE
Agent not running in same environment as Terminal

### ISSUE THREAD

**Issue by FellowTraveler** [codecompanion-ai/code-companion#95]
Notice top of image that the Agent complains that _"neo4j is not installed."_
Notice bottom of image I try **"pip install neo4j"** but it says _"Requirement already satisfied"_.

<img width="1074" alt="image" src="https://github.com/user-attachments/assets/cc04e401-8c02-42c7-80c7-cf83f05a6cdd">

**Comment by codecompanion-ai** [comment]
> Notice top of image that the Agent complains that _"neo4j is not installed."_ Notice bottom of image I try **"pip install neo4j"** but it says _"Requirement already satisfied"_.
> 
> <img alt="image" width="1074" src="https://private-user-images.githubusercontent.com/339191/350999794-cc04e401-8c02-42c7-80c7-cf83f05a6cdd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2NjA3OTUsIm5iZiI6MTcyMTY2MDQ5NSwicGF0aCI6Ii8zMzkxOTEvMzUwOTk5Nzk0LWNjMDRlNDAxLThjMDItNDJjNy04MGM3LWNmODNmMDVhNmNkZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyMlQxNTAxMzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MDE4MGZhM2QzZTAzNTNmZTQ2M2MyMzMwMWI3NjI1Y2ZiN2VlM2YwMTlkYzFlYWNkZTNkZDY5NjJkNTkwN2ZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1U5yKgwgIQ7UmGIUp5JIE5bLYQ67Qzv2ckqejaw1Dnc">

Its all running in the same environment. 

Try using a better model like Sonnet 3.5 (recommended) or GPT-4 Turbo, these should be able to handle it

**Comment by FellowTraveler** [comment]
Just FYI I'm on Mac but I'll test it.
